# Generated by Django 3.2 on 2023-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('hypertension', models.BooleanField(choices=[(0, 'Não'), (1, 'Sim')])),
                ('heart_disease', models.BooleanField(choices=[(0, 'Não'), (1, 'Sim')])),
                ('smoking_history', models.CharField(choices=[('never', 'Never'), ('no_info', 'No Info'), ('current', 'Current'), ('former', 'Former'), ('ever', 'Ever'), ('not_current', 'Not Current')], max_length=20)),
                ('bmi', models.FloatField()),
                ('HbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.BooleanField()),
            ],
        ),
    ]
