# Generated by Django 3.2 on 2023-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diabetes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
