# Generated by Django 3.2 on 2023-11-19 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paciente_diabetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='heart_disease',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='smoking_history',
        ),
    ]
